### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by humanitiesNerd** [aconchillo/guile-json#20]
Hello

I configured guile-json 1.3.0 lie this

`$ ./configure --prefix=$HOME/opt GUILD=/usr/bin/guild GUILE_CONFIG=/usr/bin/guile-config GUILE_TOOLS=/usr/bin/guile-tools`

and this is `make install`:

```
$ make install
Making install in json
make[1]: Entering directory '/home/catonano/projects/guile-json/json'
make[2]: Entering directory '/home/catonano/projects/guile-json/json'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/json'
/bin/mkdir: cannot create directory ‘/json’: Permission denied
Makefile:317: recipe for target 'install-nobase_modDATA' failed
make[2]: *** [install-nobase_modDATA] Error 1
make[2]: Leaving directory '/home/catonano/projects/guile-json/json'
Makefile:460: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/catonano/projects/guile-json/json'
Makefile:446: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

```

it attempts to create a /json folder, that is a folder in the file system root

Shouldn't it try to create a folder in the target folder ?

Thanks

**Comment by ng-0** [comment]
I can reproduce this.

```
abyayala$ cd guile-json/
abyayala$ mkdir ../out
abyayala$ pwd
/home/ng0/re-src/working-trees/guile-json
abyayala$ ./configure --prefix=$HOME/re-src/working-trees/out
bash: ./configure: No such file or directory
abyayala$ autoreconf -vif
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I build-aux
aclocal-1.15: warning: couldn't open directory 'build-aux': No such file or directory
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: creating directory build-aux
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/bin/autoconf-2.69 --force
autoreconf-2.69: configure.ac: not using Autoheader
autoreconf-2.69: running: automake --add-missing --copy --force-missing
configure.ac:26: installing 'build-aux/install-sh'
configure.ac:26: installing 'build-aux/missing'
autoreconf-2.69: Leaving directory `.'
abyayala$ ./configure --prefix=$HOME/re-src/working-trees/out
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: checking for guile 3.0
configure: checking for guile 2.2
configure: checking for guile 2.0
configure: found guile 2.0
checking for guile-2.0... no
checking for guile2.0... no
checking for guile-2... no
checking for guile2... no
checking for guile... /usr/bin/guile
checking for Guile version >= 2.0... 2.0.14
checking for guild... /usr/bin/guild
checking for guile-config... /usr/bin/guile-config
checking for Guile site directory... /usr/share/guile/site/2.0
checking for Guile site-ccache directory using pkgconfig... no
checking for Guile site-ccache directory using interpreter... /usr/lib64/guile/2.0/site-ccache
checking for Guile extensions directory... /usr/lib64/guile/2.0/extensions
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating json/Makefile
config.status: creating env
abyayala$ make install
Making install in json
make[1]: Entering directory '/home/ng0/re-src/working-trees/guile-json/json'
../env /usr/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "builder.go" "builder.scm"
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/bin/guild
;;; compiled /home/ng0/.cache/guile/ccache/2.0-LE-8-2.0/usr/bin/guild.go
wrote `builder.go'
../env /usr/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "parser.go" "parser.scm"
wrote `parser.go'
make[2]: Entering directory '/home/ng0/re-src/working-trees/guile-json/json'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/json'
/bin/mkdir: cannot create directory ‘/json’: Permission denied
make[2]: *** [Makefile:317: install-nobase_modDATA] Error 1
make[2]: Leaving directory '/home/ng0/re-src/working-trees/guile-json/json'
make[1]: *** [Makefile:459: install-am] Error 2
make[1]: Leaving directory '/home/ng0/re-src/working-trees/guile-json/json'
make: *** [Makefile:445: install-recursive] Error 1
```

**Comment by ng-0** [comment]
This seems to be normal/expected behaviour when you you don't set GUILE_SITE_DIR and other variables.

**Comment by lantw44** [comment]
It seems that it was broken by https://github.com/aconchillo/guile-json/pull/19.

Makefiles should use `GUILE_SITE`, not `GUILE_SITE_DIR`. The latter variable doesn't exist.
```diff
diff --git a/Makefile.am b/Makefile.am
index 70c295a..3546b7e 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -31,7 +31,7 @@ dist-hook:
         # '' is to make OS X happy
        sed -i '' "s/%VERSION%/$(PKG_LIST_VERSION)/g" $(top_distdir)/pkg-list.scm
 
-moddir = $(GUILE_SITE_DIR)
+moddir = $(GUILE_SITE)
 objdir = $(GUILE_SITE_CCACHE)
 
 SOURCES = json.scm
diff --git a/json/Makefile.am b/json/Makefile.am
index 8a3c3d6..0259435 100644
--- a/json/Makefile.am
+++ b/json/Makefile.am
@@ -19,7 +19,7 @@
 # along with guile-json. If not, see https://www.gnu.org/licenses/.
 #
 
-moddir = $(GUILE_SITE_DIR)/json
+moddir = $(GUILE_SITE)/json
 objdir = $(GUILE_SITE_CCACHE)/json
 
 SOURCES = builder.scm parser.scm
````

**Comment by aconchillo** [comment]
Yes, my bad. Did check fully check #19. Should be fixed in 1.3.1. Thanks!

**Comment by humanitiesNerd** [comment]
Thank you for the quick reaction, I appreciate that.

I'm sorry to bother you further but this doesn't solve the issue for me

I git pulled, made clean and made distcleaned, autoreconfed, reconfigured and rebuilt

But this is what I get

```
~/projects/guile-json$ make install
Making install in json
make[1]: Entering directory '/home/catonano/projects/guile-json/json'
make[2]: Entering directory '/home/catonano/projects/guile-json/json'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/share/guile/site/2.2/json'
/bin/mkdir: cannot create directory ‘/usr/share/guile/site’: Permission denied
Makefile:317: recipe for target 'install-nobase_modDATA' failed
make[2]: *** [install-nobase_modDATA] Error 1
make[2]: Leaving directory '/home/catonano/projects/guile-json/json'
Makefile:460: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/catonano/projects/guile-json/json'
Makefile:446: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

I'll try to send a pull request myself, later today

Thanks

**Comment by aconchillo** [comment]
I see... I'll try to fix this later. Btw, I aslo fixed something related to GUILD, GUILE_TOOLS... you shouldn't need to specify those anymore.

**Comment by humanitiesNerd** [comment]
> I see... I'll try to fix this later. Btw, I aslo fixed something related to GUILD, GUILE_TOOLS... you shouldn't need to specify those anymore.

Look, I used [this](https://erikedrosa.com/2017/10/29/guile-projects-with-autotools.html) blog post as reference and [this](https://gitlab.com/OrangeShark/guile-skeleton) project as a template

I removed all the files related to the Autotools and added thos from that project

I edited them a bit in order to adapt the names and such and tried it

It installed it

Is this approach a bit too radical for you ?

If it's ok to you, I'd test this a bit and then submit a pull request

If this is too much, I'll leave this to you

Thanks

**Comment by aconchillo** [comment]
Ohhh, I see where the problem is. Before, guile-json used:

```
moddir=$(datadir)/guile/site/$(GUILE_EFFECTIVE_VERSION)
godir=$(libdir)/guile/$(GUILE_EFFECTIVE_VERSION)/site-ccache
```

but now it uses:

```
moddir = $(GUILE_SITE)
objdir = $(GUILE_SITE_CCACHE)
```

**Comment by aconchillo** [comment]
In 1.3.2, I have reverted this change:

```
moddir = $(GUILE_SITE_DIR)
objdir = $(GUILE_SITE_CCACHE)
```

back to:

```
moddir = $(datadir)/guile/site/@GUILE_EFFECTIVE_VERSION@
objdir = $(libdir)/guile/@GUILE_EFFECTIVE_VERSION@/site-ccache
```

The reason is that the former doesn't allow a user to specify a `--prefix`. To help other users that want to install in the default directory, now you will see something like this when running configure:

```
*** guile-json 1.3.2 has been successfully configured ***

guile-json is using:

    --prefix=/usr/local --libdir=/usr/local/lib

If you want to install in Guile system's directory re-run with:

    --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu
```

or in OS X with homebrew:

```
*** guile-json 1.3.2 has been successfully configured ***

guile-json is using:

    --prefix=/usr/local --libdir=/usr/local/lib

If you want to install in Guile system's directory re-run with:

    --prefix=/usr/local/Cellar/guile/2.2.4 --libdir=/usr/local/Cellar/guile/2.2.4/lib
```

I think this should cover everyone's use case.

I have kept the guile.m4 plus some small fixes that I added for it to make it work also in old systems (e.g. Ubuntu 16.04).

**Comment by aconchillo** [comment]
Please, let me know if this works again for you. Thanks!

**Comment by humanitiesNerd** [comment]
> Please, let me know if this works again for you. Thanks!

yes, it worked

Thanks !
